# configuration for travis ci
language: node_js

os:
 - linux
 - osx

node_js:
  - "8"
  - "lts/*"
  - "node"

install:
  - npm install

before_script:
 - npm run build

script:
 - npm test
